services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: banking-app
    ports:
      - "5432:5432"

  app:
    image: muc4hit/banking-app:latest
    container_name: spring-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${DB_DOCKER_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
